config/routes.rb
Questbook::Application.routes.draw do
  resources :pins

  devise_for :users
  root "pins#index"
  get "about" => "pages#about"

  

end

app/models/pin.rb
class Pin < ActiveRecord::Base
		belongs_to :user
		has_attached_file :image, :styles => { :large => "600x600", :medium => "300x300>", :thumb => "100x100>" }

  validates :description, presence: true
  validates :image, presence: true


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :pins

  validates :name, presence: true
	validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 	before_filter :configure_permitted_parameters, if: :devise_controller?

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end 
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]


  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 12)  
  end

  def show
  end


  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)

      if @pin.save
        redirect_to @pin, notice: 'Pin was successfully created.' 
      else
        render action: 'new' 
      end
  end

  
  def update

    if @pin.update(pin_params)
       redirect_to @pin, notice: 'Pin was successfully updated.' 
    else
      render action: 'edit' 
    end
  end

 
  def destroy
    @pin.destroy
    redirect_to pins_url 
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to Edit this pin" if @pin.nil?
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class= "container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Questbook", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     
      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About Us", about_path %></li>

        <% if user_signed_in? %>
         <li><%= link_to new_pin_path do %>
                <span class="glyphicon glyphicon-plus"></span> New Pin 
            <% end %>
        </li>
          <li><%= link_to "Account Settings", edit_user_registration_path %> </li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <% else %>
           <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/_modals.html.erb
<!-- Modal -->
<div class="modal fade" id="egoCentric" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h2 class="modal-title center pomegranite" id="myModalLabel"><b>Re-Defining Egocentric!</b></h2>
      </div>
      <div class="modal-body"><div class= "jumbotron">
        Instead of like most websites where people post photos about themselves and things that they are doing, Questbook allows people to create accounts and post photos about Quest and things involving what Quest is doing 
      </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->





<!-- Modal -->
<div class="modal fade" id="getInvolved" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h2 class="modal-title center pomegranite" id="myModalLabel"><b>Get Involved!</b></h2>
      </div>
      <div class="modal-body"><div class= "jumbotron">
       <p> I am currently looking for funding. All money earned will be spent on myself and nothing but myself, you have our solemn promise. </p>

			<p> Please find me on Venmo, donations are not tax-deductable </p>
			<p> For more information, contact me <%= mail_to "qhenkart@gmail.com", "Here", class: "btn btn-success" %>
      </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<!-- Modal -->
<div class="modal fade" id="whoIs" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h2 class="modal-title center pomegranite" id="myModalLabel"><b>But, Who is Quest?</b></h2>
      </div>
      <div class="modal-body"><div class= "jumbotron">
       <p> My Name is Quest </p>
       <p> I am the Best </p>
       <p> I live in my nest </p>
       <p> and I have a nice chest </p>
        <%= link_to "Leave a Message!", "http://facebook.com/questh", class: "btn btn-success" %><p></p>
        <p> NO, I don't have a brother named adventure </p>
        <p> YES, you will get EXP for doing me </p>
        <p> that is all... </p>
      </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Questbook</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class= "container">
			<% flash.each do |name, msg| %>
    		<%= content_tag(:div, msg, class: "alert alert-info") %>
			<% end %>
			<%= yield %>
		</div>
	</body>
</html>

app/views/pages/_home.html.erb
<div class= "jumbotron center">
	<h1>Questbook</h1>
			<p>Welcome to the Questbook!</p>
			<p> Click here to</p> <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>  <br>
			<%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-sm" %>
</div>

app/views/pages/about.html.erb
<div class= "jumbotron">
		<h1> About Us </h1>
		<p> This is more about me, than about us. Questbook is a narccistic social networking site.</p>
		<p> Click on the buttons below to learn more!!</p>
	</div>

<%= render 'layouts/modals' %>

<!-- Button trigger modal -->
<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#egoCentric">
  Re-Defining Egocentric!
</button>

<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#getInvolved">
  Get Involved!
</button>

<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#whoIs">
  But, Who Is Quest?
</button>


		

app/views/pages/home.html.erb
<div class= "jumbotron center">
	<h1>Questbook</h1>
		<% if user_signed_in? %>
			<p> Welcome to the Members Area </p>
			<% else %>
			<p>Welcome to the Questbook!</p>
			<p> Click here to</p> <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>  <br>
			<%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-sm" %>
			<% end %>
</div>

app/views/pins/_form.html.erb
<%= form_for @pin, html: {multipart: true} do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-info btn-sm" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="panel panel-info">
	<div class="panel-heading">
		<h1>Edit a Photo of Quest</h1>
	</div>
	<div class="panel-body">
		<%= render 'form' %>
	</div>
	<div class="panel-footer">
		<%= link_to 'Show', @pin, class: "btn btn-default btn-xs" %> |
		<%= link_to 'Back', pins_path, class: "btn btn-default btn-xs" %>
	</div>

</div>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(pin.image.url(:medium)) , pin%>
      <div class="panel-body center">
       <%= pin.description %> </br>
        <span class="glyphicon glyphicon-user"></span><%= pin.user.name if pin.user %>
          
        <% if pin.user == current_user %>
          <div class="actions">
          <%= link_to edit_pin_path(pin), class: "btn btn-default btn-xs" do %>
              <span class="glyphicon glyphicon-edit"></span> Edit
          <%end%>
          <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn-xs" do %>
              <span class="glyphicon glyphicon-trash"></span> Delete
          <%end%>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
 <div class="center">
  <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<div class="panel panel-info">
	<div class="panel-heading">	
		<h1>Upload a new Photo of Quest</h1>
	</div>
	<div class="panel-body">

		<%= render 'form' %>
	</div>

	<div class="panel-footer">
		<%= link_to 'Back', pins_path, class: "btn btn-default btn-xs" %>
	</div>
</div>

app/views/pins/show.html.erb
<div class="row">
	<div class="col-md-offset-2 col-md-8">
		<div class="panel panel-default">
			<div class="panel-heading center">
			<%= image_tag @pin.image.url(:large) %>
			</div>
			<div class="panel-body">
			<p><%= @pin.description %> </p>
			<p><strong><%= @pin.user.name if @pin.user %></strong></p>
			<div class="panel-footer"> <%= link_to 'Back', pins_path, class: "btn btn-default btn-xs"%>
 
			<% if @pin.user == current_user %>
				<%= link_to edit_pin_path(@pin), class: "btn btn-default btn-xs" do %>

              <span class="glyphicon glyphicon-edit"></span> Edit
          <%end%>
       </div>
			<% end %>	
			</div>
		</div>
	</div>
</div>